### ISSUE TITLE
[事件] 防火墙的问题

### ISSUE THREAD

**Issue by angushushu** [FallenCrystal/CubeX-Log#106]
**描述**（单纯一个问题）
后台的akanefield开启了防火墙，需要在特定时间手动关闭吗？还是会在攻击停止后自动解除呢？
咱也不知道面对攻击能干啥，有啥需要我做的就说

**Comment by FallenCrystal** [comment]
本来就应该是开启了 idk你设置了什么策略

**Comment by angushushu** [comment]
嗷，我不是说系统防火墙，我以为BC里面开了什么导致玩家进不去。我重启一下BC？

**Comment by FallenCrystal** [comment]
> 嗷，我不是说系统防火墙，我以为BC里面开了什么导致玩家进不去。我重启一下BC？

bc没有防火墙. AkaneField也只会断开连接 idk你想说什么

**Comment by angushushu** [comment]
我想说玩家现在连接不进去，我想解决一下

**Comment by angushushu** [comment]
已修复
