### ISSUE TITLE
[Bug] 玩家在受攻击时进入被列入Akanefield黑名单

### ISSUE THREAD

**Issue by angushushu** [FallenCrystal/CubeX-Log#107]
**描述**
zimin和其他几个玩家被列入了黑名单，尝试了Akanefield的config里写的sudo ipset del删除后重启了BC仍然在黑名单中。

**复现**
sudo ipset del akanefield <IP>
重启BC
黑名单中仍然有该玩家IP

**预期行为**
玩家可以正常进入

**附加内容**
重启BC是需要的么？

**Comment by FallenCrystal** [comment]
iptables是彻底阻止 那是系统自带黑名单 否则不可能会显示阻止消息
尝试使用命令`/af clear blacklist`

**Comment by FallenCrystal** [comment]
不过idk为什么需要疯狂重连我不是很理解那些人 难不成我还需要列出个rule指定在攻击期间内不可以做什么?

> `奇怪的玩家` 是指同ip在大约1秒内建立了两次连接或其它东西 这是一个综合检查 但我不觉得这会导致非常多的正常玩家被列入黑名单 并且它也并没有被iptables列入黑名单.

**Comment by angushushu** [comment]
了解了，尝试了af clear blacklist但是出现报错
![image](https://user-images.githubusercontent.com/23127549/226148892-d8cd9412-1a18-4d78-bb6c-621a82f00eb3.png)

**Comment by FallenCrystal** [comment]
那是消息发送时出错 之后会尝试修复 但黑名单应该被正确清理。 `/af stats`

**Comment by angushushu** [comment]
目前看好像没有清除，我再试一下让他两分钟后连接试试

**Comment by FallenCrystal** [comment]
> 我问zimin他说没有重复连接  

说实话我觉得他们这些*"垃圾邮件发送者"* 肯定是会干出这种行为的

**Comment by FallenCrystal** [comment]
![image](https://user-images.githubusercontent.com/71176602/226148947-33a2b08e-9a8c-4095-bb0b-bc131062dbe4.png)

**Comment by angushushu** [comment]
让他又连了一次，还是不行。说是和上次截图（大概1-2分钟以前）中间没有连过

**Comment by angushushu** [comment]
看到加入白名单了，我一分钟后让他再试一下

**Comment by FallenCrystal** [comment]
![image](https://user-images.githubusercontent.com/71176602/226149082-7e9289b5-a01a-41ec-8113-f80a08932ec6.png)
![image](https://user-images.githubusercontent.com/71176602/226149089-92635540-7483-4943-8175-f7a08604c14e.png)
![image](https://user-images.githubusercontent.com/71176602/226149097-442e8a80-1b61-43b7-884d-7ba7fe2fb6fa.png)
![image](https://user-images.githubusercontent.com/71176602/226149112-429ddd46-1ca9-4d1c-a4c4-048b186e9f21.png)
![image](https://user-images.githubusercontent.com/71176602/226149119-7e79252a-a0c0-4571-a0d4-688d4d7a5039.png)

**Comment by angushushu** [comment]
能进了，多亏有你
昨天攻击前是可以进的，之后一直是黑名单，应该就单纯是攻击的时候被joincheck误封了加上我不会解？
总之谢谢

**Comment by FallenCrystal** [comment]
当ip被加入到白名单时 应该会自动从blacklist内删除并跳过所有检查.

**Comment by FallenCrystal** [comment]
> > 了解了，尝试了af clear blacklist但是出现报错 ![image](https://user-images.githubusercontent.com/23127549/226148892-d8cd9412-1a18-4d78-bb6c-621a82f00eb3.png) 我问zimin他说没有重复连接
> 
> track [CatMoe/AkaneField#7 (comment)](https://github.com/CatMoe/AkaneField/issues/7#issue-1635812004)

Fixed this issue on https://github.com/CatMoe/AkaneField/commit/fab95f795fa43d6f0a7cd297aa1ae25a4af9bbf5#diff-511b0078b3ee2cef531437892ad9501414dc7d963901a7f60ca2c5c17d9d937e
