### ISSUE TITLE
[Bug] 服务器连接问题与资源占用

### ISSUE THREAD

**Issue by angushushu** [FallenCrystal/CubeX-Log#109]
**描述**
1. 24号早晨开始服务器显示在线但无法加入（login server down？），服务端正常。出现该问题时ssh与vnc无法连接，解决方法是硬重启。推测是资源占用问题导致的。
2. 与该问题交错出现的是无法连接到服务器（服务器列表种也加载不出来）。目前服务器处于该问题状态。
在出现问题1之前更新过protocolizer和AkaneField，并且修改过global.cubexmc.org的CNAME（从国际线路改为国内线路）。回退AkaneField版本后暂时没用出现问题1，但问题2尚未解决正在与供应商联系。

供应商需要确认vps系统层面除ipset还有没有其他改动以方便排查可能的原因。

**Comment by FallenCrystal** [comment]
这几天Minecraft API在维护. 具体之后的再通知吧 我这边也经常连不上

**Comment by FallenCrystal** [comment]
我也只是在说问题1..

**Comment by angushushu** [comment]
现在1倒是暂时解决了，但是供应商再问2的系统改动，要排查一下

**Comment by FallenCrystal** [comment]
> 现在1倒是暂时解决了，但是供应商再问2的系统改动，要排查一下。开这个issue跟你确认一下有哪些改动

~~我说没解决就是没解决~~


> 这几天Minecraft API在维护. 具体之后的再通知吧 我这边也经常连不上

**Comment by FallenCrystal** [comment]
idk 我基本没有用过iptables和ipset的经验 akanefield只是根据config里面的内容执行命令而已 我不知道除了修改配置文件它会改动什么

> 也可能是国际线路的IP被firewalled了 如果你正在用国际线路

**Comment by angushushu** [comment]
OK有你这句就行了，确认一下
